AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Booker Backend API using AWS SAM

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs18.x
    Environment:
      Variables:
        NODE_ENV: production

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production

Resources:
  # API Gateway
  BookingsApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: booker-api
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"
      DefinitionBody:
        openapi: "3.0.1"
        info:
          title: Booker API
          version: "1.0"
        paths:
          /health:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HealthCheckFunction.Arn}/invocations"
          /bookings:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetBookingsFunction.Arn}/invocations"
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateBookingFunction.Arn}/invocations"
          /bookings/{id}:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetBookingFunction.Arn}/invocations"
            put:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateBookingFunction.Arn}/invocations"
            delete:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteBookingFunction.Arn}/invocations"

  # Health Check Function
  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: functions/health/
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BookingsApi
            Path: /health
            Method: get

  # Get Bookings Function
  GetBookingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: functions/getBookings/
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDBSecret
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BookingsApi
            Path: /bookings
            Method: get

  # Get Booking Function
  GetBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: functions/getBooking/
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDBSecret
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BookingsApi
            Path: /bookings/{id}
            Method: get

  # Create Booking Function
  CreateBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: functions/createBooking/
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDBSecret
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BookingsApi
            Path: /bookings
            Method: post

  # Update Booking Function
  UpdateBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: functions/updateBooking/
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDBSecret
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BookingsApi
            Path: /bookings/{id}
            Method: put

  # Delete Booking Function
  DeleteBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: functions/deleteBooking/
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDBSecret
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BookingsApi
            Path: /bookings/{id}
            Method: delete

  # MongoDB Secret (reference to existing secret)
  MongoDBSecret:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /booker/mongodb-uri

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${BookingsApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"

  HealthCheckUrl:
    Description: Health check endpoint
    Value: !Sub "https://${BookingsApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/health"
